name: preview
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  permission_handler: ^11.3.1
  dio: ^5.7.0
  path_provider: ^2.1.0
  isar_flutter_libs: ^4.0.0-dev.13
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
